### ISSUE TITLE
Bug determining expired keys in accountsMgr.diff()

### ISSUE THREAD

**Issue by nickkortman** [GoogleCloudPlatform/guest-agent#157]
[This block](https://github.com/GoogleCloudPlatform/guest-agent/blob/main/google_guest_agent/non_windows_accounts.go#:~:text=%7D-,//%20If%20any%20on%2Ddisk%20keys%20have%20expired.,%7D,-//%20If%20we%27ve%20just) uses `getUserKeys` to determine if there are any keys that have expired since the last iteration. However, the keys in `sshKeys` are not of the format that `getUserKeys` expects (no "user:" prefix), so they always hit [this block](https://github.com/GoogleCloudPlatform/guest-agent/blob/main/google_guest_agent/non_windows_accounts.go#:~:text=idx%20%3A%3D%20strings.Index,%7D), which means that `getUserKeys` returns an empty list, and `diff` always returns true.

**Comment by hopkiw** [comment]
Thanks for catching this, Nick. You're right, we're unnecessarily reconciling users' ssh keys every minute. Luckily, this is the good kind of failure mode, compared to not refreshing them :)

We are considering replacing this logic with an SSH authorized keys command, as we do with OS Login. We will either fix this bug or make that transition. Will leave this issue open for tracking or any discussion.

**Comment by rogerhub** [comment]
Hi, can we have this fixed? It's causing confusing log spam for me:

```
2022-07-17 19:20:28.202 PDT non_windows_accounts.go:199] Invalid ssh key entry - unrecognized format: ssh-rsa ...
```

Without context, this message suggests that the guest agent might not be updating SSH keys properly, which is alarming. It looks like this bug was introduced in #142? @gaohannk Any thoughts about this?

Thanks!

**Comment by hopkiw** [comment]
that message does suggest your agent is not updating keys properly. i don't believe it is related to this issue.

**Comment by rogerhub** [comment]
The same underlying bug causes both the unnecessary refresh as well as the log spam.

I work on GCE by the way :)
