### ISSUE TITLE
Publish recent release packages

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/guest-agent#183]
The last release published to https://launchpad.net/ubuntu/+source/google-guest-agent (for Focal) is 20220622. Six releases have been made since then, and we're affected by a bug<sup>1</sup> that looks like it was fixed in 20220927 specifically. Is it possible to have a new deb published? Should I open an issue for that on launchpad?

Alternatively, should we be adding a different apt repo to our GCE instances to get these updates?

---

<sup>1</sup>https://github.com/GoogleCloudPlatform/guest-agent/issues/157#issuecomment-1186709146, which I think is affecting quite a few people based on the dates of google search results.

**Comment by hopkiw** [comment]
Hi  @zbjornson 

Thanks  for filing this issue. Ultimately Canonical makes their own decisions about updating this software, but we will file a case with them to take updates.

We do not currently offer any directly available packages for Ubuntu, but if you file an issue  requesting it, we can track it as a feature request.

**Comment by zbjornson** [comment]
Thank you @hopkiw !

**Comment by vorakl** [comment]
Hey @zbjornson, 
It seems a new release (20230330.00) finally made its way into Ubuntu (Lunar).
I'm closing the issue.
