### ISSUE TITLE
Load secrets from Google Secret Manager

### ISSUE THREAD

**Issue by jawnsy** [GoogleCloudPlatform/guest-agent#190]
Cloud Run can automatically mount secrets from Secret Manager, and it would be nice if the guest agent or https://github.com/GoogleCloudPlatform/konlet could do the same thing

**Comment by hopkiw** [comment]
Thanks for your FR. This would be far outside the scope of the guest agent, but feel free to file an issue to the konlet repo if you think it may be appropriate there.
