### ISSUE TITLE
shutdown script run on update of package

### ISSUE THREAD

**Issue by markusher** [GoogleCloudPlatform/guest-agent#208]
I am running a ubuntu 22.04 image and the apt-daily-upgrade.timer is active. This causes an update of packages and when updating the guest agent package it runs the shutdown script. This makes our software make a clean shutdown as we expect that the node will be terminated. It is however not, so we now have a dead node.
As a workaround I disabled the daily apt update in order to not kill our nodes and activated healthchecks in the instance group. But I dont think the shutdown script should run for an update of the guest agent package.

I do have some logs that I can send if required

**Comment by vorakl** [comment]
Thank you for the bug report!
This is a known issue, please read this comment and below in another thread:  https://github.com/GoogleCloudPlatform/guest-agent/issues/119#issuecomment-1535170965

The thing is that Canonical has its own build process and they have a bug in the package for that particular version.
I'm closing this Issue as duplicate to the existing one.
