### ISSUE TITLE
Error on latest version

### ISSUE THREAD

**Issue by llomgui** [GoogleCloudPlatform/guest-agent#283]
Hello,

I updated rhel-7 servers today to the latest version:
```
---> Package google-guest-agent.x86_64 1:20230601.00-g1.el7 will be updated
---> Package google-guest-agent.x86_64 1:20230913.00-g1.el7 will be an update
```

Since this update, It spams (more than 10 millions in less than 15 minutes) the proxy server with the following calls:
`15/Sep/2023:11:30:20 +0200      0 10.10.33.62 TCP_DENIED/403 4013 GET http://169.254.169.254/computeMetadata/v1//? - HIER_NONE/- text/html`

Am I missing something? It was working fine before this update.

Thank you

**Comment by dorileo** [comment]
Hi @llomgui 

Can you pease try [disabling telemetry](https://github.com/GoogleCloudPlatform/guest-agent#telemetry) and seeing if the behavior goes away?

**Comment by dorileo** [comment]
Can you also please share the lines in your squid configuration for `allow` and `deny` rules? Can you tell if it's not matching the url `http://169.254.169.254/computeMetadata/v1//?`, paying special attention to this `//` part of the path?

**Comment by dorileo** [comment]
> Hi @llomgui
> 
> Can you pease try [disabling telemetry](https://github.com/GoogleCloudPlatform/guest-agent#telemetry) and seeing if the behavior goes away?

Looking back to it I believe this is not related to telemetry.

**Comment by llomgui** [comment]
Hello @dorileo,

I found the root cause. It was due to a missconfiguration in the NetworkManager. `/etc/resolv.conf` file was not generated correctly.

That's why the calls were with `169.254.169.254` ip instead of `metadata` domain. The NO_PROXY variable was not able to work.
