### ISSUE TITLE
https://fonts.googleapis.com

### ISSUE THREAD

**Issue by Lyllt8** [GoogleCloudPlatform/guest-agent#330]
https://github.com/Lyllt8/video-localized-narratives/blob/main/index.html#L22

**Comment by ChaitanyaKulkarni28** [comment]
This doesn't look like anything related to Guest Agent, closing this.

**Comment by justinclift** [comment]
Note that this user appears to be a bot, creating issues with random text in repos. :frowning:

(found by them submitting multiple issues like this to the sqlitebrowser repos)

I've just reported this account to GitHub ("spammer").  Hopefully they'll nuke it.
