### ISSUE TITLE
google_metadata_script_runner: last few seconds of logs are not flushed to Cloud Logging

### ISSUE THREAD

**Issue by rkolchmeyer** [GoogleCloudPlatform/guest-agent#358]
I noticed that the following startup-script:

```
#!/bin/bash
echo hello
```

does not upload any logs to Cloud Logging. I also noticed that the following startup-script:

```
#!/bin/bash
echo hello
sleep 10
```

_does_ upload logs to Cloud Logging.

I've also noticed that more complicated startup scripts appear to be missing the last few lines of their log in Cloud Logging. It seems to me that the last few seconds of startup script logs are not uploaded to Cloud Logging. This is particularly problematic for startup scripts that are really fast.

**Comment by ChaitanyaKulkarni28** [comment]
I have not tested this but it seems like [this](https://github.com/GoogleCloudPlatform/guest-logging-go/blob/master/logger/logger.go#L105-L110) is the issue. Logs are flushed every 5 seconds thus losing last few logs as process exits.
