### ISSUE TITLE
Wrong commit tagged as 20240716.00

### ISSUE THREAD

**Issue by glaubitz** [GoogleCloudPlatform/guest-agent#406]
I just wanted to update the `guest-agent` package in openSUSE to the version `20240716.00` and noticed that the `network/manager` subfolder is missing while it's still missing on `main`.

Also, looking at the tag [1], it seems the latest changes there are two month old:

```
glaubitz@suse-laptop:~/upstream/guest-agent> git show 20240716.00|head -n20
commit 5723ac468ba402b0056f66e529fbd076982f6371
Author: Leandro (Leo) Dorileo <dorileo@google.com>
Date:   Sat May 25 07:21:33 2024 +0000

    update dep: golang.org/x/crypto to v0.17.0

diff --git a/go.mod b/go.mod
index ab9ee3e..00b0bec 100644
--- a/go.mod
+++ b/go.mod
@@ -18,8 +18,8 @@ require (
        github.com/kardianos/service v1.2.1
        github.com/robfig/cron/v3 v3.0.1
        github.com/tarm/serial v0.0.0-20180830185346-98f6abe2eb07
-       golang.org/x/crypto v0.14.0
-       golang.org/x/sys v0.13.0
+       golang.org/x/crypto v0.17.0
+       golang.org/x/sys v0.15.0
        google.golang.org/grpc v1.57.1
        google.golang.org/protobuf v1.33.0
glaubitz@suse-laptop:~/upstream/guest-agent>
```

I assume that the wrong commited was tagged as `20240716.00`.

> [1] https://github.com/GoogleCloudPlatform/guest-agent/tree/20240716.00

**Comment by ChaitanyaKulkarni28** [comment]
That is correct, `main` branch has some bug we found in network manager that you see missing, and is being worked upon. We rolled back those changes released in `20240701.00` to previous stable version and released it as `20240716.00`.
