### ISSUE TITLE
Broken fallback from systemd-networkd to dhclient

### ISSUE THREAD

**Issue by aaronmaxlevy** [GoogleCloudPlatform/guest-agent#470]
`‎systemdNetworkd.IsManaging‎` is not properly handling the scenario in which `networkctl` is not installed. 

Currently, if you test with e.g. v20241031, you will get the following error logged:
```
google_guest_agent[1069]: ERROR main.go:139 [&main.addressMgr{}] Failed to run manager Set() call: failed to setup network interfaces: error detecting network manager service: error checking networkctl version: exec: "networkctl": executable file not found in $PATH
```

The issue is that the code at https://github.com/GoogleCloudPlatform/guest-agent/blob/43ca38dac145ddc5dcaaf91b9c3bc29b77531965/google_guest_agent/network/manager/systemd_networkd_linux.go#L187  should be returning false if the boolean return value from calling `cliExists("networkctl")` is false, even if an error is not returned (`cliExists` returns a `nil` error if the CLI in question just isn't installed).

**Comment by ChaitanyaKulkarni28** [comment]
Thanks for reporting and fixing the issue @aaronmaxlevy

**Comment by aaronmaxlevy** [comment]
No problem @ChaitanyaKulkarni28 ! Thanks for the quick review and merge!
