### ISSUE TITLE
Cleanup references to distro logic that should be generic

### ISSUE THREAD

**Issue by zmarano** [GoogleCloudPlatform/guest-agent#51]
In this PR, we are fixing when to disable NetworkManager but doing it only for distro logic which we assume to be the case. Instead, we should actually look for NetworkManager to be active (installed or otherwise) to do this as opposed to only looking for what we know the baseline case to be for EL7/8.

https://github.com/GoogleCloudPlatform/guest-agent/pull/50

**Comment by gaohannk** [comment]
Closed (https://github.com/GoogleCloudPlatform/guest-agent/pull/63) after discussion with @hopkiw
