### ISSUE TITLE
Building google-guest-agent on openSUSE/SLE fails with "undefined: errors.Is"

### ISSUE THREAD

**Issue by glaubitz** [GoogleCloudPlatform/guest-agent#60]
I'm currently working on packaging ```guest-agent``` for openSUSE/SLE [1]. While ```google_metadata_script_runner``` builds fine, ```google-guest-agent``` fails with the following error:

```
[    5s] + pushd google_guest_agent
[    5s] ~/rpmbuild/BUILD/guest-agent-20200630.00+git20200630.5b11764/google_guest_agent ~/rpmbuild/BUILD/guest-agent-20200630.00+git20200630.5b11764
[    5s] + CGO_ENABLED=0
[    5s] + go build '-ldflags=-s -w -X main.version=20200630.00+git20200630.5b11764' -mod=vendor
[    5s] # github.com/GoogleCloudPlatform/guest-agent/google_guest_agent
[    5s] ./main.go:256:25: undefined: errors.Is
```
FWIW, I'm building with ```-mod=vendor``` as we don't allow accessing the internet during build time (like it's standard for most Linux distributions).

From the error, it looks like the ```errors``` class used in our case does not support the ```Is()``` yet.

CC @rjschwei

> [1] https://build.opensuse.org/package/show/home:glaubitz:branches:Cloud:Tools/google-guest-agent

**Comment by glaubitz** [comment]
It looks like ```errors.Is()``` was added in Go 1.13 [1], while ```go.mod``` has the requirement for Go 1.12.

> [1] https://golang.org/pkg/errors/#Is

**Comment by runlevel5** [comment]
FYI I could reproduce this issue on Go 1.12.12

**Comment by glaubitz** [comment]
It builds fine for me with Go 1.14, I didn't test 1.13.

**Comment by ChaitanyaKulkarni28** [comment]
`go.mod` is updated to `1.20`
