### ISSUE TITLE
google-guest-agent.service interferes with policy routing

### ISSUE THREAD

**Issue by jeffmccune** [GoogleCloudPlatform/guest-agent#76]
Overview
===

Using a centos-cloud/centos8 multinic VM instance as an IP router between two VPC networks, [Policy Routing](https://cloud.google.com/vpc/docs/create-use-multiple-interfaces#configuring_policy_routing) is configured as below.  When `systemctl restart google-guest-agent.service` happens, Policy Routing is reconfigured in a way that breaks IP routing.

Expected behavior
===

I expected DHCP and Google Guest Agent to limit route table modifications to the `main` tables, but not the user defined tables 10 and 11 below:

```
[jeff@multinic-a-x9w3 ~]$ sudo ip route list table main
default via 10.33.0.1 dev eth0 proto dhcp metric 100
10.33.0.0/20 via 10.33.0.1 dev eth0 proto dhcp metric 100
10.33.0.1 dev eth0 proto dhcp scope link metric 100
10.37.0.0/20 via 10.37.0.1 dev eth1 proto static
10.37.0.0/20 via 10.37.0.1 dev eth1 proto dhcp metric 101
10.37.0.1 dev eth1 scope link
10.37.0.1 dev eth1 proto dhcp scope link metric 101
[jeff@multinic-a-x9w3 ~]$ sudo ip route list table 10
default via 10.33.0.1 dev eth0
10.33.0.1 dev eth0 scope link
10.37.0.1 dev eth1 scope link
[jeff@multinic-a-x9w3 ~]$ sudo ip route list table 11
default via 10.37.0.1 dev eth1
10.33.0.1 dev eth0 scope link
10.37.0.1 dev eth1 scope link
```

Actual behavior:
===

`systemctl restart google-guest-agent.service` (or DHCP renew after 24 hours) breaks policy routing:

```
# sudo ip route show table 11 | tee before
default via 10.37.0.1 dev eth1
10.33.0.1 dev eth0 scope link
10.37.0.1 dev eth1 scope link

# sudo systemctl restart google-guest-agent.service

# sudo ip route show table 11 | tee after
10.33.0.1 dev eth0 scope link
```

Steps to reproduce:
===

Setup policy routing using a script similar to the following.  Note, I'm happy to change this script to be compatible with `google-guest-agent.service` if there's a way to do so, the intent of the script is to send traffic ingress to nic0 out nic1 and vice-versa, while also supporting ILB health checks coming into both interfaces.

```
#! /bin/bash
# These tables manage default routes based on policy.
if ! grep -qx '10 nic0' /etc/iproute2/rt_tables; then
  echo "10 nic0" >> /etc/iproute2/rt_tables
fi
if ! grep -qx '11 nic1' /etc/iproute2/rt_tables; then
  echo "11 nic1" >> /etc/iproute2/rt_tables
fi

## These are essentially the same tables, just different default gateways.
# Traffic addresses attached to the nic0 primary interface
ip route add default via "10.33.0.1" dev eth0 table nic0
ip route add "10.33.0.1" dev eth0 scope link table nic0
ip route add "10.37.0.1" dev eth1 scope link table nic0
# Traffic addresses attached to the nic1 primary interface
ip route add default via "10.37.0.1" dev eth1 table nic1
ip route add "10.33.0.1" dev eth0 scope link table nic1
ip route add "10.37.0.1" dev eth1 scope link table nic1

# NOTE: These route rules are not cleared by dhclient, they persist.
ip rule add from "10.33.0.54" table nic0
ip rule add from "10.37.0.54" table nic1
# ILB IP addresses are expected to be in the nic's subnet.
ip rule add from "10.33.0.54/20" table nic0
ip rule add from "10.37.0.54/20" table nic1
# Firewall marking
iptables -A PREROUTING -i eth0 -t mangle -j MARK --set-mark 1
iptables -A PREROUTING -i eth1 -t mangle -j MARK --set-mark 2
# Packets ingress nic0 egress nic1
ip rule add fwmark 1 table nic1
# Packets ingress nic1 egress nic0
ip rule add fwmark 2 table nic0
# Netblocks via VPC default gateways
ip route flush cache
ip rule
```

Related: https://github.com/GoogleCloudPlatform/compute-image-packages/issues/475

My own efforts to troubleshoot this are at:
 * https://github.com/openinfrastructure/terraform-google-multinic/issues/10
 * https://github.com/openinfrastructure/terraform-google-multinic/pull/13

**Comment by jeffmccune** [comment]
@hopkiw Thanks for taking a look at this issue.  Here's what I found:

Root Cause
---

The [Policy Routing](https://cloud.google.com/vpc/docs/create-use-multiple-interfaces#configuring_policy_routing) tables break when the guest-agent calls `dhclient -x` [here](https://github.com/GoogleCloudPlatform/guest-agent/blob/20200826.00/google_guest_agent/addresses.go#L520).  The chain of events is:

 1. `systemctl restart google-guest-agent`
 2. dhclient -x
 3. `/usr/sbin/dhclient-script` with `reason=STOP`
 4. `/sbin/ip -4 addr del 10.0.0.1/32 dev eth1` where 10.0.0.1 is the address assigned by DHCP
 5. As a side effect of ip addr del, all routes in all tables associated with the IP address are also deleted.

The good news is DHCP renewal does not affect the routing tables or policy routing.  I only observe this issue when restarting the guest-agent.

Workaround
---

The workaround I'm employing avoids the call to `remove_old_addr` in `/usr/sbin/dhclient-script` with something like [this](https://gist.github.com/jeffmccune/4671d9aeb90a0a3f122e058cbdf7c6f0).

```bash
# /etc/dhcp/dhclient-down-hooks
# Make sure to chmod a+x this file or dhclient-script won't source it
logmessage "Workaround for https://github.com/GoogleCloudPlatform/guest-agent/issues/76"
exit_with_hooks 0
```

Proposed solution
---

To fix this problem and avoid the workaround, what do you think about a PR I'm happy to draft that takes the following approach?

 1. Delegate process cleanup to systemd by specifying `KillMode=control-group` in the service unit file.  dhclient documentation says it will not execute dhclient-script when signaled.
 2. Set `Environment=SKIP_DHCLIENT_X=yes` in the systemd unit file
 3. Modify [addresses.go](https://github.com/GoogleCloudPlatform/guest-agent/blob/20200826.00/google_guest_agent/addresses.go#L520) to skip the call to `dhclient -x` if SKIP_DHCLIENT_X is yes

My assumption is the guest-agent is calling `dhclient -x` to clean up any stale dhclient processes after service stop / start cycles, but I'm not certain.  I couldn't figure it out from the code comments or commit messages.  If this is the case, we can safely delegate to systemd to handle process cleanup.  I've verified systemd signals dhclient, which terminates gracefully without deleting the ip addresses or any routes.

What do you think?  I'm happy to work on a PR for this, or discuss another approach.

**Comment by hopkiw** [comment]
It's not clear why we would need step 3 with an "if" when in step 2 we're guaranteeing the environment variable will always be present. 

If we remove `dhclient -x`, whether conditionally or not, we may pile up dhclient processes. The guest agent doesn't know the state at startup - is this a first boot, or is it a restart, or startup after a crash? So for safety, we kill existing dhclient processes with `dhclient -x` and start the ones that should exist.

**Comment by hopkiw** [comment]
Also, we still support some non-systemd distributions. 

> "dhclient documentation says it will not execute dhclient-script when signaled"

can you share this documentation? the manpage doesn't mention this.

**Comment by jeffmccune** [comment]
@hopkiw Thanks for following up.

> It's not clear why we would need step 3 with an "if" when in step 2 we're guaranteeing the environment variable will always be present.
> Also, we still support some non-systemd distributions.

My intent for `SKIP_DHCLIENT_X=yes` is to change the `dhclient -x` behavior only when running in the context of systemd, which cleans up the process group.  For non-systemd distributions `dhclient -x` behavior doesn't change, hence the conditional.

> If we remove dhclient -x, whether conditionally or not, we may pile up dhclient processes.

I'd like to better understand the situations they pile up.  Here's what I've thought about / tried:

 1. guest-agent crashes
 2. guest-agent receives a signal (e.g. SIGTERM)
 3. guest-agent is killed with kill -9
 4. systemctl stop google-guest agent

For 1, I haven't tested it but I'm fairly certain systemd will kill the control-group and reap the dhclient process.

For the others, I've tested `Restart=always` and `KillMode=control-group` cleans up the child dhclient process nicely.

> The guest agent doesn't know the state at startup - is this a first boot, or is it a restart, or startup after a crash?

I think in all three cases it's OK to just execute `dhclient ethX` and let systemd handle cleaning up and resetting state for the next start.

> So for safety, we kill existing dhclient processes with dhclient -x and start the ones that should exist.

Thanks for confirming the reason `dhclient -x` is there, I agree with the intent but the method is having the opposite effect since it makes an unsafe `ip addr del` call.

>> "dhclient documentation says it will not execute dhclient-script when signaled"

> can you share this documentation? the manpage doesn't mention this.

Read it here: https://linux.die.net/man/8/dhclient (which annoyingly doesn't mention -x other than this paragraph.)

"If the client is killed by a signale (for example at shutdown or reboot), it will not execute the dhclient-script (8) at exit. However, if you shut the client down gracefully with -r or -x it will execute dhclient-script (8) at shutdown with the specific reason for calling the script set in the environment table."

**Comment by hopkiw** [comment]
Thanks for this thorough investigation. I think this only leaves the case of whether some other dhclient process is running, and we should decide if that's OK. And whether `KillMode=control-group` will have any other side effects for other guest behavior.

**Comment by jeffmccune** [comment]
How do you want other dhclient process handled?  My suggestion is to limit
the guest-agent kill behavior to processes it creates, not kill others.
For example, a dhclient eth0 process should likely be left alone.

There shouldn't be any KillMode=control-group side effects, it's is the
systemd default so behavior won't change.  Adding it explicitly because
guest-agent depends on the behavior once dhclient -x is removed.
