### ISSUE TITLE
Cloud logging fails due to metadata value propagation

### ISSUE THREAD

**Issue by zmarano** [GoogleCloudPlatform/guest-agent#93]
The agent's cloud logging export fails since #82.

```
google_guest_agent[411]: 2020/12/14 18:11:02 logging client: rpc error: code = InvalidArgument desc = Name "projects//logs/GCEGuestAgent" is missing the parent component. Expected the form projects/[PROJECT_ID]/logs/[ID]
```

The project string is empty (not getting populated from metadata). This isn't distro specific and is consistent with the updated agent.

**Comment by hopkiw** [comment]
this was caused by delaying the metadata host lookup. should be fixed in incoming PR
